<?xml version="1.0"?>
<!-- Revolute-Revolute Manipulator -->
<robot name="antropomorphic_arm" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Constants for robot dimensions -->
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="mass" value="1.0" />
  <xacro:property name="mass_axis" value="0.01" />

  <xacro:property name="r1" value="0" /> 
  <xacro:property name="r2" value="1.0" /> 
  <xacro:property name="r3" value="1.0" />
  <xacro:property name="alpha_1" value="${PI/2}" /> 
  <xacro:property name="alpha_2" value="0" /> 
  <xacro:property name="alpha_3" value="0" /> 

  <xacro:property name="scale_dim" value="1.0" />
  <xacro:property name="base_z_displacement" value="0.0" /> 

  <xacro:property name="link_base_bb_x" value="1.0" /> 
  <xacro:property name="link_base_bb_y" value="1.0" /> 
  <xacro:property name="link_base_bb_z" value="0.1" /> 

  <xacro:property name="link_1_bb_x" value="0.5" /> 
  <xacro:property name="link_1_bb_y" value="0.5" /> 
  <xacro:property name="link_1_bb_z" value="1.0" /> 

  <xacro:property name="link_2_bb_x" value="1.24412" /> 
  <xacro:property name="link_2_bb_y" value="0.488246" /> 
  <xacro:property name="link_2_bb_z" value="0.488246" /> 

  <xacro:property name="link_3_bb_x" value="1.39221" /> 
  <xacro:property name="link_3_bb_y" value="0.488246" /> 
  <xacro:property name="link_3_bb_z" value="0.488246" /> 

  <xacro:property name="joint_lim_effort" value="1000.0" /> 
  <xacro:property name="joint_lim_vel" value="3.0" /> 

  <xacro:property name="joint_2_lim_low" value="${-PI/4}" /> 
  <xacro:property name="joint_2_lim_high" value="${5*PI/4}" /> 

  <xacro:property name="joint_3_lim_low" value="${-3*PI/4}" /> 
  <xacro:property name="joint_3_lim_high" value="${3*PI/4}" /> 

  <xacro:property name="axis_bb" value="0.788" />
  <xacro:property name="frame0_z_displacement" value="1.000" />
  <xacro:property name="scale_axis_dim" value="1.0" />
  
  <xacro:property name="d_i" value="0.31123" />
  <xacro:property name="theta_i" value="${-PI/4}" />
  <xacro:property name="r_i" value="0.825129" />
  <xacro:property name="alpha_i" value="${-PI/2}" />
  

  <xacro:macro name="box_inertia" params="mass x y z">
    <inertia  ixx="${mass*(y*y+z*z)/12.0}" ixy = "0" ixz = "0"
              iyy="${mass*(x*x+z*z)/12.0}" iyz = "0"
              izz="${mass*(x*x+y*y)/12.0}"
    />
  </xacro:macro>

  <xacro:macro  name="cylinder_inertia" params="mass r l">
      <inertia  ixx="${mass*(3*r*r+l*l)/12}" ixy = "0" ixz = "0"
                iyy="${mass*(3*r*r+l*l)/12}" iyz = "0"
                izz="${mass*(r*r)/2}" />
  </xacro:macro >


  <xacro:include filename="$(find antropomorphic_arm_description)/robot/antropomorphic_arm.gazebo" />

  <link name="world"/>

  <!-- Extra visual frames-->
  <link name="frame_0">

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
          <geometry>
                <mesh filename="package://antropomorphic_arm_description/meshes/axis_frame_0.dae" scale="${scale_axis_dim} ${scale_axis_dim} ${scale_axis_dim}"/>
          </geometry>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${mass_axis}"/>
      <xacro:box_inertia mass="${mass_axis}" x="${axis_bb}" y="${axis_bb}" z="${axis_bb}"/>
    </inertial>
  </link>


  <joint name="fixed_frame_0" type="fixed">
    <origin xyz="0 0 ${frame0_z_displacement}" rpy="0 0 0"/>
    <parent link="world"/>
    <child link="frame_0"/>
  </joint>

  <link name="link_base">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
          <geometry>
                <mesh filename="package://antropomorphic_arm_description/meshes/antropomorfic_arm_link_base.dae" scale="${scale_dim} ${scale_dim} ${scale_dim}"/>
          </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
          <geometry>
                <mesh filename="package://antropomorphic_arm_description/meshes/antropomorfic_arm_link_base.dae" scale="${scale_dim} ${scale_dim} ${scale_dim}"/>
          </geometry>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <xacro:box_inertia mass="${mass}" x="${link_base_bb_x}" y="${link_base_bb_y}" z="${link_base_bb_z}"/>
    </inertial>
  </link>

  <joint name="fixed_world_to_base_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <parent link="world"/>
    <child link="link_base"/>
  </joint>

  <link name="link_1">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
          <geometry>
                <mesh filename="package://antropomorphic_arm_description/meshes/antropomorfic_arm_link_1.dae" scale="${scale_dim} ${scale_dim} ${scale_dim}"/>
          </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
          <geometry>
                <mesh filename="package://antropomorphic_arm_description/meshes/antropomorfic_arm_link_1.dae" scale="${scale_dim} ${scale_dim} ${scale_dim}"/>
          </geometry>
    </visual>

    <inertial>
      <origin xyz="0 0 ${link_1_bb_z/2}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <xacro:box_inertia mass="${mass}" x="${link_1_bb_x}" y="${link_1_bb_y}" z="${link_1_bb_z}"/>
    </inertial>
  </link>

  <joint name="joint1" type="continuous">
    <parent link="link_base"/>
    <child link="link_1"/>
    <origin xyz="0 0 ${base_z_displacement}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <!-- Extra visual frames-->
  <link name="frame_1">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
          <geometry>
                <mesh filename="package://antropomorphic_arm_description/meshes/axis_frame_3.dae" scale="${scale_axis_dim} ${scale_axis_dim} ${scale_axis_dim}"/>
          </geometry>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${mass_axis}"/>
      <xacro:box_inertia mass="${mass_axis}" x="${axis_bb}" y="${axis_bb}" z="${axis_bb}"/>
    </inertial>
  </link>


  <joint name="fixed_frame_1" type="fixed">
    <origin xyz="${r1} 0 ${frame0_z_displacement}" rpy="${alpha_1} 0 0"/>
    <parent link="link_1"/>
    <child link="frame_1"/>
  </joint>
  

    
  
  <transmission name="tran1">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint1">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor1">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>


  <!-- LINK 2-->
  <link name="link_2">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
          <geometry>
                <mesh filename="package://antropomorphic_arm_description/meshes/antropomorfic_arm_link_2.dae" scale="${scale_dim} ${scale_dim} ${scale_dim}"/>
          </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
          <geometry>
                <mesh filename="package://antropomorphic_arm_description/meshes/antropomorfic_arm_link_2.dae" scale="${scale_dim} ${scale_dim} ${scale_dim}"/>
          </geometry>
    </visual>

    <inertial>
      <origin xyz="${link_2_bb_x/2 - 0.243241} 0 0" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <xacro:box_inertia mass="${mass}" x="${link_2_bb_x}" y="${link_2_bb_y}" z="${link_2_bb_z}"/>
    </inertial>
  </link>

  <joint name="joint2" type="revolute">
    <parent link="frame_1"/>
    <child link="link_2"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="${joint_2_lim_low}" upper="${joint_2_lim_high}" effort="${joint_lim_effort}" velocity="${joint_lim_vel}"/>
  </joint>


  <link name="frame_2">

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
          <geometry>
                <mesh filename="package://antropomorphic_arm_description/meshes/axis_frame_3.dae" scale="${scale_axis_dim} ${scale_axis_dim} ${scale_axis_dim}"/>
          </geometry>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${mass_axis}"/>
      <xacro:box_inertia mass="${mass_axis}" x="${axis_bb}" y="${axis_bb}" z="${axis_bb}"/>
    </inertial>
  </link>


  <joint name="fixed_frame_2" type="fixed">
    <origin xyz="${r2} 0 0" rpy="${alpha_2} 0 0"/>
    <parent link="link_2"/>
    <child link="frame_2"/>
  </joint>

    
  
  <transmission name="tran2">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint2">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor2">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>


  <!-- LINK 3 -->

  <link name="link_3">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
          <geometry>
                <mesh filename="package://antropomorphic_arm_description/meshes/antropomorfic_arm_link_3.dae" scale="${scale_dim} ${scale_dim} ${scale_dim}"/>
          </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
          <geometry>
                <mesh filename="package://antropomorphic_arm_description/meshes/antropomorfic_arm_link_3.dae" scale="${scale_dim} ${scale_dim} ${scale_dim}"/>
          </geometry>
    </visual>

    <inertial>
      <origin xyz="${link_3_bb_x/2 - 0.243241} 0 0" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <xacro:box_inertia mass="${mass}" x="${link_3_bb_x}" y="${link_2_bb_y}" z="${link_3_bb_z}"/>
    </inertial>
  </link>

  <joint name="joint3" type="revolute">
    <parent link="frame_2"/>
    <child link="link_3"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="${joint_3_lim_low}" upper="${joint_3_lim_high}" effort="${joint_lim_effort}" velocity="${joint_lim_vel}"/>
  </joint>


  <link name="frame_3">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
          <geometry>
                <mesh filename="package://antropomorphic_arm_description/meshes/axis_frame_3.dae" scale="${scale_axis_dim} ${scale_axis_dim} ${scale_axis_dim}"/>
          </geometry>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${mass_axis}"/>
      <xacro:box_inertia mass="${mass_axis}" x="${axis_bb}" y="${axis_bb}" z="${axis_bb}"/>
    </inertial>
  </link>


  <joint name="fixed_frame_3" type="fixed">
    <origin xyz="${r3} 0 0" rpy="${alpha_3} 0 0"/>
    <parent link="link_3"/>
    <child link="frame_3"/>
  </joint>

    
  
  <transmission name="tran3">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint3">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor3">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  
 
</robot>
